### ISSUE TITLE
Double and single quotes

### ISSUE THREAD

**Issue by hector6872** [x2bool/kuery#12]
Some strings are enclose between double quotes but it shouldn't be so (reference: https://www.sqlite.org/lang_select.html)

https://github.com/x2bool/kuery/blob/master/sqlite/src/com/nivabit/kuery/sqlite/SQLiteDialect.kt#L480
https://github.com/x2bool/kuery/blob/master/sqlite/src/com/nivabit/kuery/sqlite/SQLiteDialect.kt#L484
https://github.com/x2bool/kuery/blob/master/sqlite/src/com/nivabit/kuery/sqlite/SQLiteDialect.kt#L488
https://github.com/x2bool/kuery/blob/master/sqlite/src/com/nivabit/kuery/sqlite/SQLiteDialect.kt#L53

There isn't a problem if you want me to make a PR about this.

**Comment by x2bool** [comment]
Hi! Double quotes are used for table and column names.

https://www.sqlite.org/lang_keywords.html

> If you want to use a keyword as a name, you need to quote it.

That is the main reason. What kind of problems do you have with double quotes? Does the library produce invalid SQL?

**Comment by hector6872** [comment]
There they talk about using "SQL keywords" as table or column name (doing that is a little weird...)

Actually it works but I'm used to see SQL statements without that double quotes :)

**Comment by x2bool** [comment]
Yeah! I think it would be wise to leave quotes just in case someone accidentally uses a keyword as a table name.

**Comment by hector6872** [comment]
You're right :) 

But, what do you think about put Strings between single quotes? 
I mean, currently I have to use this extension on Strings types:

`private fun String.toQuoted() = "\"${this}\""`

`from(Table).where { (it.api eq api.toQuoted()) } ...`

**Comment by x2bool** [comment]
Treating strings literally was a mistake. The right way probably is to put strings into single quotes.

That said there are few things to consider:
* Single quotes within the string itself should be escaped in some way
* Strings are not sanitized at the moment of building a query. I should document that and make it really clear that using a string in a statement could be dangerous
* There should be a way to pass literal values like "?" (and maybe other expressions???)

Otherwise I am up for PRs and changes )
